# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacora',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.IntegerField(verbose_name='Tel\xe9fono')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='ContactoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'ContactoTipo',
                'verbose_name_plural': 'ContactoTipo',
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Envios',
                'verbose_name_plural': 'Envios',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensaje',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.IntegerField(verbose_name='C\xf3digo telef\xf3nico')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Trivia',
                'verbose_name_plural': 'Trivia',
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='contactotipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacaosms.ContactoTipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Pais', verbose_name='Pa\xeds'),
        ),
    ]
