# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Agrupaci\xf3n',
                'verbose_name_plural': 'Agrupaci\xf3n',
            },
        ),
        migrations.AlterModelOptions(
            name='envios',
            options={'ordering': [], 'verbose_name': 'Env\xedos', 'verbose_name_plural': 'Env\xedos'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['nombre'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensaje'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['nombre'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuesta'},
        ),
        migrations.AlterModelOptions(
            name='trivia',
            options={'ordering': ['nombre'], 'verbose_name': 'Trivia', 'verbose_name_plural': 'Trivia'},
        ),
        migrations.AddField(
            model_name='bitacora',
            name='de',
            field=models.IntegerField(default=0, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='mensaje',
            field=models.CharField(default='', max_length=160, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='para',
            field=models.IntegerField(default=0, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envios',
            name='de',
            field=models.CharField(default=0, max_length=100, verbose_name='Qui\xe9n env\xeda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envios',
            name='para_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Contacto', verbose_name='Para un n\xfamero espec\xedfico'),
        ),
        migrations.AddField(
            model_name='envios',
            name='para_contactotipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.ContactoTipo', verbose_name='Para todo un tipo de contacto'),
        ),
        migrations.AddField(
            model_name='envios',
            name='para_pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Pais', verbose_name='Para todo un pa\xeds'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje',
            field=models.CharField(default='', max_length=160, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='mensaje',
            field=models.CharField(default=django.utils.timezone.now, max_length=160, verbose_name='Mensaje de respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='nombre',
            field=models.CharField(default='', max_length=160, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='nombre',
            field=models.CharField(default='', max_length=160, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='contactotipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.ContactoTipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='envios',
            name='para_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Grupo', verbose_name='Para un grupo'),
        ),
    ]
