# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0002_auto_20161128_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Mensaje', verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='envios',
            name='texto',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Mensaje personalizado'),
        ),
    ]
