# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0003_auto_20161128_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Estado de env\xedo',
                'verbose_name_plural': 'Estado de env\xedo',
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='recibidos',
            field=models.IntegerField(blank=True, null=True, verbose_name='recibidos'),
        ),
        migrations.AddField(
            model_name='envios',
            name='envios_programados',
            field=models.IntegerField(blank=True, null=True, verbose_name='envios_programados'),
        ),
        migrations.AddField(
            model_name='envios',
            name='envios_realizados',
            field=models.IntegerField(blank=True, null=True, verbose_name='envios_realizados'),
        ),
        migrations.AddField(
            model_name='envios',
            name='finalizada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha real finalizada'),
        ),
        migrations.AddField(
            model_name='envios',
            name='programada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha programada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='enviados',
            field=models.IntegerField(blank=True, null=True, verbose_name='enviados'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='de',
            field=models.IntegerField(verbose_name='de'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='mensaje',
            field=models.CharField(max_length=160, verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='para',
            field=models.IntegerField(verbose_name='para'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.CharField(max_length=160, verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='nombre',
            field=models.CharField(max_length=160, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='nombre',
            field=models.CharField(max_length=160, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='envios',
            name='estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Estado', verbose_name='estado'),
            preserve_default=False,
        ),
    ]
