# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0005_auto_20161128_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='grupo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='grupo',
            field=models.ManyToManyField(to='cacaosms.Grupo', verbose_name='Grupos'),
        ),
    ]
