# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0006_auto_20170125_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='fecha',
            new_name='fecha_envio',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='envio_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='estado',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_resultado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='resultado',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='envios',
            name='para',
            field=models.IntegerField(blank=True, null=True, verbose_name='Para tel\xe9fono espec\xedfico'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='de',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='para',
            field=models.CharField(max_length=32),
        ),
    ]
