# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0008_auto_20170203_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='nombre',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
