# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cacaosms', '0009_auto_20170205_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contacto', models.ManyToManyField(blank=True, to='cacaosms.Contacto', verbose_name='Para un n\xfamero espec\xedfico')),
                ('contactotipo', models.ManyToManyField(blank=True, to='cacaosms.ContactoTipo', verbose_name='Para todo un tipo de contacto')),
                ('grupo', models.ManyToManyField(blank=True, to='cacaosms.Grupo', verbose_name='Para un grupo')),
                ('pais', models.ManyToManyField(blank=True, to='cacaosms.Pais', verbose_name='Para todo un pa\xeds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Permisos',
                'verbose_name_plural': 'Permisos',
            },
        ),
    ]
