# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0010_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trivia',
            options={'ordering': ['respuesta', 'nombre'], 'verbose_name': 'Trivia', 'verbose_name_plural': 'Trivia'},
        ),
        migrations.AddField(
            model_name='respuesta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='is_trivia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='mensaje',
            field=models.CharField(default='', max_length=160, verbose_name='Mensaje de respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='respuesta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='super',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Trivia'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='nombre',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='nombre',
            field=models.CharField(max_length=32, unique=True, verbose_name='Mensaje recibido'),
        ),
    ]
