# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0011_auto_20170206_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='nombre',
            field=models.CharField(max_length=32, verbose_name='Mensaje recibido'),
        ),
    ]
