# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0012_auto_20170206_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMSBackend', models.CharField(choices=[(b'dummy', b'Dummy'), (b'mail', b'E-mail'), (b'twilio', b'Twilio'), (b'nexmo', b'Nexmo'), (b'plivo', b'Plivo')], default=b'dummy', max_length=32)),
            ],
            options={
                'verbose_name': 'SMS Configuration',
            },
        ),
        migrations.CreateModel(
            name='TriviaEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('de', models.CharField(max_length=32, unique=True, verbose_name='N\xfamero de tel\xe9fono')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Trivia')),
            ],
            options={
                'ordering': ['fecha', 'de'],
                'verbose_name': 'Trivia Estado',
                'verbose_name_plural': 'Trivia Estado',
            },
        ),
        migrations.AlterField(
            model_name='envios',
            name='programada',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha programada'),
        ),
    ]
