# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0014_auto_20170208_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaestado',
            name='estado',
        ),
        migrations.AddField(
            model_name='triviaestado',
            name='respuesta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triviaestado',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Trivia'),
        ),
    ]
