# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0015_auto_20170208_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Tel\xe9fono'),
        ),
    ]
